### ISSUE TITLE
úkol 1 - Togi

### ISSUE THREAD

**Issue by Togi12** [Togi12/python-kurz-2022#1]
odevzdávám úkol 1 - https://github.com/Togi12/python-kurz-2022/blob/main/ukol-01.py

akorát mi to hází nějakej chybnej výsledek a moc nechápu proč:

Jaky je kod vaseho baliku? B947X

Balík byl předán kurýrovi.
Balík zatím nebyl předán kurýrovi.
Balík zatím nebyl předán kurýrovi.
Balík byl předán kurýrovi.
Balík zatím nebyl předán kurýrovi.

**Comment by pixelneo** [comment]
```
kod_baliku = input("Jaky je kod vaseho baliku?")
```
tady se to promenne kod_baliku priradi vstup od uzivatele.


```
for kod_baliku, stav in baliky.items():
```
tady se ale do promenne kod_baliku prirazuji klice v tom dictionary (postupne, jak se prochazi cyklus).

Je to tedy potreba udelat jinak. Napovim, ze lze pouzit operator `in` z lekce a neni potreba prochazet cely `dict` pomoci `for`.

**Comment by Togi12** [comment]
opraveno https://github.com/Togi12/python-kurz-2022/blob/main/ukol-01.py

**Comment by Togi12** [comment]
prosím o kontrolu @pixelneo (myslím, že mi to funguje OK). Díky!

**Comment by pixelneo** [comment]
Ahoj, jo funguje, díky.

Malá poznámka: Operátor `is` není nejlepší používat (`baliky[kod_baliku] is True`). Lepší je buď `==` nebo tady by stačilo `baliky[kod_baliku] `. 

`is` neporovnává přímo hodnotu, ale ten takzvaný objekt, a třeba při porovnání listů pomocí `is` už by to (většinou) nefungovalo.
