### ISSUE TITLE
úkol 2 - Togi

### ISSUE THREAD

**Issue by Togi12** [Togi12/python-kurz-2022#2]
https://github.com/Togi12/python-kurz-2022/blob/main/ukol-02.py

tady vůbec nevím, jak na to :(

**Comment by Togi12** [comment]
@pixelneo mohl by ses podívat na ten kód a poradit, jak by to správně mělo být? hlásí mi to chybu a já nevím, jak to opravit. Děkujuu

**Comment by pixelneo** [comment]
Ahoj @Togi12, skoro to mas.. chyba byla v `print(staty['name'])` melo tam byt `print(country['name'])`.

Ukol povazuji za dokonceny :-) 

Kdyztak se zeptej, kdyby neco nebylo jasne.

**Comment by Togi12** [comment]
opraveno, funguje. Moc díky!
