### ISSUE TITLE
Togi - ukol4

### ISSUE THREAD

**Issue by Togi12** [Togi12/python-kurz-2022#4]
Ahoj, rovnou posílám i 4. úkol: https://github.com/Togi12/python-kurz-2022/blob/main/ukol-04.py

Díky, Togi

**Comment by Togi12** [comment]
akorát tady koukám, že jsem neudělala, tu změnu stavu.. ale nějak nemůžu přijít na to, jak na to..

**Comment by pixelneo** [comment]
Ahoj, jo ` self.stav == False` dve rovnitka `==` jsou operator porovnani, melo by tam byt jen jedno.
Je to malickost, ukol uz povazjuji za dokonceny :-).

Taky pripominka... `if self.stav is True:` neni idealni. Lepsi je bud `if self.stav:` nebo alespon `if self.stav == True:`.
Tady funguji vsechny tyto moznosti, ale operator `is` dela neco jineho trochu jineho, a treba pri porovnani stringu, listu, dictu by to nemuse fungovat tak jak je to mysleno.
Pro zajimavost, treba [tady](https://www.geeksforgeeks.org/difference-operator-python/) jsou nejake priklady operatoru `is`.
